FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Hacketon Lunchers

Fill some description :)

# Today's menu

## Homepage [/api/menu]

### List of all [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "rest_id": 1,
                    "title": "Halong Bay",
                    "menu": [
                        {
                            "title": "Menu 1",
                            "price": "110 Kč"
                        },
                        {
                            "title": "Menu 2",
                            "price": "120 Kč"
                        },
                        {
                            "title": "Menu 3",
                            "price": "80 Kč"
                        },
                        {
                            "title": "Menu 4",
                            "price": ""
                        }
                    ]
                },
                {
                    "rest_id": 2,
                    "title": "Jiná Krajina",
                    "menu": [
                        {
                            "title": "Steak z Tuňáka",
                            "price": "130 Kč"
                        },
                        {
                            "title": "Cheeseburger a domácí hranolky",
                            "price": "120 Kč"
                        },
                        {
                            "title": "Vegetariánské Burritos",
                            "price": "115 Kč"
                        },
                        {
                            "title": "Hovězí tatarák",
                            "price": "140 Kč"
                        }
                    ]
                },
                {
                    "rest_id": 3,
                    "title": "The Pub",
                    "menu": [
                        {
                            "title": "Steak z Tuňáka",
                            "price": "130 Kč"
                        },
                        {
                            "title": "Chicken Caesar salát",
                            "price": "90 Kč"
                        },
                        {
                            "title": "Plněné bramborové knedlíky uzeným masem",
                            "price": "115 Kč"
                        },
                        {
                            "title": "Hovězí tatarák",
                            "price": "140 Kč"
                        }
                    ]
                }
            ]

