FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Hacketon Lunchers

Fill some description :)

# Today's menu

## Homepage [/api/menu]

### List of all [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "rest_id": 1,
                    "title": "Halong Bay",
                    "slug": "halong-bay",
                    "menu": [
                        {
                            "title": "Menu 1",
                            "price": "110 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Menu 2",
                            "price": "120 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Menu 3",
                            "price": "80 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Pálivá polévka",
                            "price": "20 Kč",
                            "type": "soup",
                            "description": ""
                        }
                    ]
                },
                {
                    "rest_id": 2,
                    "title": "Jiná Krajina",
                    "slug": "jina-krajina",
                    "menu": [
                        {
                            "title": "Steak z Tuňáka",
                            "price": "130 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Cheeseburger a domácí hranolky",
                            "price": "120 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Vegetariánské Burritos",
                            "price": "115 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Hovězí tatarák",
                            "price": "140 Kč",
                            "type": "",
                            "description": ""
                        }
                    ]
                },
                {
                    "rest_id": 3,
                    "title": "The Pub",
                    "slug": "the-pub",
                    "menu": [
                        {
                            "title": "Steak z Tuňáka",
                            "price": "130 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Chicken Caesar salát",
                            "price": "90 Kč",
                            "type": "",
                             "description": ""
                        },
                        {
                            "title": "Plněné bramborové knedlíky uzeným masem",
                            "price": "115 Kč",
                            "type": "",
                            "description": ""
                        },
                        {
                            "title": "Hovězí tatarák",
                            "price": "140 Kč",
                            "type": "",
                             "description": ""
                        }
                    ]
                }
            ]

